### ISSUE TITLE
Mejoras estéticas

### ISSUE THREAD

**Issue by fdodino** [AR-Beauty-and-Make-up/AR-Beauty-and-Make-up#3]
- Agregar ícono
- "AR Beauty & make up"
- mousePointer para el menú de opciones
- la selección de los servicios lo pone en blanco, no ayuda a ver qué se selecciona: quizás usar bold, quizás aumentar ligeramente el tamaño o usar un gradiente más oscuro para ayudar a resaltar las letras blancas

**Comment by LucianaAlonso** [comment]
Terminado.
